// This file was autogenerated by gulp-closure-deps plugin.
// Please do not edit.
goog.addDependency('../../../../scenes/jamband/js/audio.js', ['app.Audio'], [], false);
goog.addDependency('../../../../scenes/jamband/js/dragdrop.js', ['app.DragDrop'], [], false);
goog.addDependency('../../../../scenes/jamband/js/drawer.js', ['app.Drawer'], [], false);
goog.addDependency('../../../../scenes/jamband/js/fallback.js', ['app.Fallback'], [], false);
goog.addDependency('../../../../scenes/jamband/js/game.js', ['app.Game'], ['app.DragDrop', 'app.Drawer', 'app.Fallback', 'app.Instruments', 'app.Lights', 'app.shared.ShareOverlay'], false);
goog.addDependency('../../../../scenes/jamband/js/instruments.js', ['app.Instruments'], ['app.Audio', 'app.Fallback'], false);
goog.addDependency('../../../../scenes/jamband/js/lights.js', ['app.Lights'], [], false);
goog.addDependency('../../../../scenes/shared/js/coordinator.js', ['app.shared.Coordinator'], [], false);
goog.addDependency('../../../../scenes/shared/js/effect.js', ['app.shared.Effect'], ['app.shared.SharedGame', 'app.shared.utils'], false);
goog.addDependency('../../../../scenes/shared/js/framerpc.js', ['app.shared.FrameRPC'], [], false);
goog.addDependency('../../../../scenes/shared/js/gameover.js', ['app.shared.Gameover'], ['app.shared.Overlay', 'app.shared.ShareButtons', 'app.shared.SharedGame', 'app.shared.utils'], false);
goog.addDependency('../../../../scenes/shared/js/imagepreloader.js', ['app.shared.ImagePreloader'], [], false);
goog.addDependency('../../../../scenes/shared/js/inputevent.js', ['app.InputEvent'], [], false);
goog.addDependency('../../../../scenes/shared/js/levelup.js', ['app.shared.LevelUp'], ['app.shared.SharedGame', 'app.shared.utils'], false);
goog.addDependency('../../../../scenes/shared/js/overlay.js', ['app.shared.Overlay'], ['app.shared.utils'], false);
goog.addDependency('../../../../scenes/shared/js/pause-overlay.js', ['app.shared.PauseOverlay'], ['app.shared.Overlay'], false);
goog.addDependency('../../../../scenes/shared/js/pools.js', ['app.shared.pools'], [], false);
goog.addDependency('../../../../scenes/shared/js/scene-board.js', ['app.shared.Sceneboard'], ['Constants', 'app.shared.SharedScene', 'app.shared.utils'], false);
goog.addDependency('../../../../scenes/shared/js/scoreboard.js', ['app.shared.Scoreboard'], ['Constants', 'app.shared.SharedGameOver'], false);
goog.addDependency('../../../../scenes/shared/js/share-buttons.js', ['app.shared.ShareButtons'], ['app.shared.utils'], false);
goog.addDependency('../../../../scenes/shared/js/share-overlay.js', ['app.shared.ShareOverlay'], ['app.shared.Overlay', 'app.shared.ShareButtons', 'app.shared.utils'], false);
goog.addDependency('../../../../scenes/shared/js/shared-game.js', ['app.shared.SharedGame'], ['app.shared.Scoreboard', 'app.shared.SharedGameOver'], false);
goog.addDependency('../../../../scenes/shared/js/shared-gameover.js', ['app.shared.SharedGameOver'], [], false);
goog.addDependency('../../../../scenes/shared/js/shared-scene.js', ['app.shared.SharedScene'], [], false);
goog.addDependency('../../../../scenes/shared/js/tutorial.js', ['app.shared.Tutorial'], [], false);
goog.addDependency('../../../../scenes/shared/js/utils.js', ['app.shared.utils'], [], false);